package model.common.serviceinterface;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import model.common.PartsViewSDO;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 19 05:50:11 EDT 2014
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="/model/common/", name="AppModuleService", wsdlLocation="model/common/serviceinterface/AppModuleService.wsdl")
@SDODatabinding(schemaLocation="model/common/serviceinterface/AppModuleService.xsd")
public interface AppModuleService {
    public static final String NAME = "{/model/common/}AppModuleService";

    @WebMethod(action="/model/common/findPartsView1WithPartIdList", operationName="findPartsView1WithPartIdList")
    @RequestWrapper(targetNamespace="/model/common/types/", localName="findPartsView1WithPartIdList")
    @ResponseWrapper(targetNamespace="/model/common/types/", localName="findPartsView1WithPartIdListResponse")
    @WebResult(name="result")
    List<PartsViewSDO> findPartsView1WithPartIdList(@WebParam(mode = WebParam.Mode.IN, name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="PartIdList")
        String PartIdList, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;
}
