package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 04 14:26:08 EDT 2014
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    String whoseYourDaddy();
}
