package model;

import model.common.AppModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 04 14:25:35 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }
    
    public String whoseYourDaddy() {
        return "I am";
    }

    /**
     * Container's getter for WidgetView1.
     * @return WidgetView1
     */
    public ViewObjectImpl getWidgetView1() {
        return (ViewObjectImpl)findViewObject("WidgetView1");
    }

    /**
     * Container's getter for JDemoView1.
     * @return JDemoView1
     */
    public ViewObjectImpl getJDemoView1() {
        return (ViewObjectImpl)findViewObject("JDemoView1");
    }

    /**
     * Container's getter for CandyView1.
     * @return CandyView1
     */
    public ViewObjectImpl getCandyView1() {
        return (ViewObjectImpl)findViewObject("CandyView1");
    }
}
