package model;

import oracle.jbo.ViewCriteriaItem;
import oracle.jbo.domain.Array;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 19 05:39:06 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PartsViewImpl extends ViewObjectImpl {
    
    private String escapedList = null;
    
    /**
     * This is the default constructor (do not remove).
     */
    public PartsViewImpl() {
    }
    
    /**
     *
     * @param vci
     * @return
     */
    public String getCriteriaItemClause(ViewCriteriaItem vci) {
      if (vci.getAttributeDef().getName().equals("Part") &&
        vci.getViewCriteria().getName().contains("WithPartIdList")) {
        if (vci.getViewCriteria().getRootViewCriteria().isCriteriaForQuery()) {
        return getINClauseForDatabaseUse(vci);
        } else {
        return getINClauseForCache(vci);
        }
      } else {
        return super.getCriteriaItemClause(vci);
      }

    }

    /**
     *
     * @param vci
     * @return
     */
    protected String getINClauseForDatabaseUse(ViewCriteriaItem vci) {

      String whereClause = "1=1";
      if (getPartIdList() != null) {
          
          if(escapedList == null) {
              escapedList = "'" + getPartIdList().replaceAll(",", "','") + "'";
              System.out.println("+++++++++ getINClauseForDatabaseUse().  Resetting the PartIdList to escaped version: " + escapedList);
              setPartIdList(escapedList);
          }
          
          whereClause = this.getEntityDef(0).getAliasName() + ".PART IN (" + escapedList + ") AND (:PartIdList IS NOT NULL)";
          System.out.println("+++++++++ getINClauseForDatabaseUse().  Adding custom WHERE clause: " + whereClause);
      }
      return whereClause;
    }

    /**
     *
     * @param vci
     * @return
     */
    protected String getINClauseForCache(ViewCriteriaItem vci) {
      String whereClause = "1=1";
      return whereClause;
    }

    /**
     * Returns the variable value for PartIdArray.
     * @return variable value for PartIdArray
     */
    public String getPartIdList() {
        return (String)ensureVariableManager().getVariableValue("PartIdList");
    }

    /**
     * Sets <code>value</code> for variable PartIdArray.
     * @param value value to bind as PartIdArray
     */
    public void setPartIdList(String value) {
        ensureVariableManager().setVariableValue("PartIdList", value);
    }
}
